# Generated by Django 5.2.11 on 2026-04-19 00:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.TextField(unique=True)),
                ("first_seen_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "participants",
            },
        ),
        migrations.CreateModel(
            name="LogEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=200)),
                (
                    "participant_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("event", models.CharField(max_length=100)),
                ("data", models.JSONField(default=dict)),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, unpack_ipv4=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "log_events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["participant_id"], name="log_events_partici_50f11c_idx"
                    ),
                    models.Index(fields=["event"], name="log_events_event_96b542_idx"),
                    models.Index(
                        fields=["session_id"], name="log_events_session_c81349_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.TextField(unique=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("screen_w", models.IntegerField(blank=True, null=True)),
                ("screen_h", models.IntegerField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        db_column="participant_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="LessonPlanHelper.participant",
                        to_field="participant_id",
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
            },
        ),
        migrations.CreateModel(
            name="PromptSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.TextField(blank=True, null=True)),
                (
                    "submission_type",
                    models.TextField(
                        choices=[
                            ("pretest", "Pretest"),
                            ("fullpractice", "Full Practice"),
                            ("posttest", "Posttest"),
                        ]
                    ),
                ),
                ("attempt_number", models.IntegerField(default=1)),
                ("prompt_text", models.TextField(blank=True, null=True)),
                ("score_goal", models.IntegerField(blank=True, null=True)),
                ("score_context", models.IntegerField(blank=True, null=True)),
                ("score_task", models.IntegerField(blank=True, null=True)),
                ("score_constraints", models.IntegerField(blank=True, null=True)),
                ("score_output", models.IntegerField(blank=True, null=True)),
                ("total_score", models.IntegerField(blank=True, null=True)),
                ("overall_feedback", models.TextField(blank=True, null=True)),
                (
                    "edited_fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LessonPlanHelper.session",
                        to_field="session_id",
                    ),
                ),
            ],
            options={
                "db_table": "prompt_submissions",
            },
        ),
        migrations.CreateModel(
            name="GenerateEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.TextField(blank=True, null=True)),
                ("generate_type", models.TextField(blank=True, null=True)),
                ("prompt_text", models.TextField(blank=True, null=True)),
                ("ai_output", models.TextField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LessonPlanHelper.session",
                        to_field="session_id",
                    ),
                ),
            ],
            options={
                "db_table": "generate_events",
            },
        ),
        migrations.CreateModel(
            name="ButtonClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.TextField(blank=True, null=True)),
                ("button_name", models.TextField(blank=True, null=True)),
                ("total_clicks", models.IntegerField(blank=True, null=True)),
                ("module_id", models.IntegerField(blank=True, null=True)),
                ("step_index", models.IntegerField(blank=True, null=True)),
                ("step_type", models.TextField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LessonPlanHelper.session",
                        to_field="session_id",
                    ),
                ),
            ],
            options={
                "db_table": "button_clicks",
            },
        ),
        migrations.CreateModel(
            name="AnnotatedDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.TextField(blank=True, null=True)),
                ("expected_type", models.TextField(blank=True, null=True)),
                ("dragged_type", models.TextField(blank=True, null=True)),
                ("correct", models.BooleanField(blank=True, null=True)),
                ("dropped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LessonPlanHelper.session",
                        to_field="session_id",
                    ),
                ),
            ],
            options={
                "db_table": "annotated_drops",
            },
        ),
        migrations.CreateModel(
            name="StepTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_id", models.TextField(blank=True, null=True)),
                ("module_id", models.IntegerField(blank=True, null=True)),
                ("step_index", models.IntegerField(blank=True, null=True)),
                ("step_type", models.TextField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LessonPlanHelper.session",
                        to_field="session_id",
                    ),
                ),
            ],
            options={
                "db_table": "step_times",
            },
        ),
    ]
