# Generated by Django 5.2.11 on 2026-04-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LessonPlanHelper", "0002_analysis_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotateddrop",
            name="session",
        ),
        migrations.RemoveField(
            model_name="generateevent",
            name="session",
        ),
        migrations.RemoveField(
            model_name="session",
            name="participant",
        ),
        migrations.RemoveField(
            model_name="steptime",
            name="session",
        ),
        migrations.RemoveField(
            model_name="promptsubmission",
            name="session",
        ),
        migrations.RemoveField(
            model_name="buttonclick",
            name="session",
        ),
        migrations.AlterModelOptions(
            name="buttonclick",
            options={"ordering": ["clicked_at"]},
        ),
        migrations.AlterModelOptions(
            name="promptsubmission",
            options={"ordering": ["submitted_at"]},
        ),
        migrations.AlterModelOptions(
            name="steptime",
            options={"ordering": ["entered_at"]},
        ),
        migrations.RemoveIndex(
            model_name="logevent",
            name="log_events_session_c81349_idx",
        ),
        migrations.RenameField(
            model_name="steptime",
            old_name="recorded_at",
            new_name="entered_at",
        ),
        migrations.RemoveField(
            model_name="buttonclick",
            name="total_clicks",
        ),
        migrations.AddField(
            model_name="steptime",
            name="exited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="AnnotatedDrop",
        ),
        migrations.DeleteModel(
            name="GenerateEvent",
        ),
        migrations.DeleteModel(
            name="Session",
        ),
    ]
