# Generated by Django 5.2.13 on 2026-05-05 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LessonPlanHelper', '0004_new_rubric_dimensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module2Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.CharField(choices=[('opening', 'Opening'), ('desired_results', 'Desired Results'), ('learner_context', 'Learner & Context'), ('evidence_of_learning', 'Evidence of Learning'), ('instructional_plan', 'Instructional Plan'), ('output_requirements', 'Output Requirements'), ('context_summary', 'Context Summary'), ('lesson_generation', 'Lesson Generation'), ('local_adjustment', 'Local Adjustment'), ('final_review', 'Final Review'), ('completed', 'Completed')], default='opening', max_length=100)),
                ('completion_status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=50)),
                ('global_context_json', models.JSONField(default=dict)),
                ('generated_lesson_json', models.JSONField(default=dict)),
                ('revised_lesson_json', models.JSONField(default=dict)),
                ('final_lesson_json', models.JSONField(default=dict)),
                ('section_feedback_json', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module2_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'module2_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalContextSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_results', models.JSONField(default=dict)),
                ('learner_context', models.JSONField(default=dict)),
                ('evidence_of_learning', models.JSONField(default=dict)),
                ('instructional_plan', models.JSONField(default=dict)),
                ('output_requirements', models.JSONField(default=dict)),
                ('required_learning_goal_text', models.TextField(blank=True)),
                ('required_local_context_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context_survey', to='LessonPlanHelper.module2session')),
            ],
            options={
                'db_table': 'global_context_surveys',
            },
        ),
    ]
